# A dummy zkVM using WHIR for testing WHIR

[zkevm]
name = "DummyWHIR"
protocol_family = "WHIR"
field = "Goldilocks^2"
hash_size_bits = 256

[[circuits]]
name = "main"
log_inv_rate = 2  # rate 1/4
num_iterations = 5
folding_factor = 4
log_degree = 23
batch_size = 100
power_batching = true
constraint_degree = 3
num_queries = [119, 47, 29, 22, 18]
num_ood_samples = [2, 2, 2, 2]

# grinding
grinding_bits_batching = 10
grinding_bits_folding = [[10, 10, 10, 10], [10, 10, 10, 10], [10, 10, 10, 10], [10, 10, 10, 10], [10, 10, 10, 10]]
grinding_bits_queries = [15, 15, 15, 8, 8]
grinding_bits_ood = [0, 0, 0, 0]
